### ISSUE TITLE
OpenSubsonic auth error

### ISSUE THREAD

**Issue by stkw0** [Taiko2k/Tauon#1112]
I'm not sure if it's an issue with LMS (the subsonic server I use) or tauon, but since some other subsonic clients work with LMS I thought could be useful to report it here.

When trying to log it reports the next error. I also tried using plain text but then it fails directly. Even if the root cause is not an issue with tauon It would be nice if tauon could at least properly parse the error and show it to the user.
```python
Subsonic Error: {"subsonic-response":{"openSubsonic":true,"serverVersion":"6","status":"failed","type":"lms","version":"1.16.0","error":{"code":41,"message":"Token authentication not supported for LDAP users."}}}
Exception in thread Thread-28 (get_music3):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.11/site-packages/t_modules/t_main.py", line 8638, in get_music3
    b = a["subsonic-response"]["indexes"]["index"]
        ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'indexes'
```

**Comment by Taiko2k** [comment]
Do you get any kind of error when plain text mode is enabled?

**Comment by stkw0** [comment]
Nope, in plain text mode there is just a messagebox saying that there was an authentication failure but the console doesn't shows anything.

**Comment by C0rn3j** [comment]
Can you do `print(a["subsonic-response"])` above the problematic line to see what's in it?

**Comment by stkw0** [comment]
In the latest reelase, 7.8.3, it give the next error
```
Exception in thread Thread-16 (getsongs):
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.12/site-packages/t_modules/t_main.py", line 8857, in getsongs
    if item["isDir"]:
       ~~~~^^^^^^^^^
KeyError: 'isDir'
Exception in thread Thread-17 (getsongs):
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.12/site-packages/t_modules/t_main.py", line 8866, in getsongs
    getsongs(index, item["id"], item["title"], inner=True, parent=item)
  File "/usr/lib/python3.12/site-packages/t_modules/t_main.py", line 8857, in getsongs
Exception in thread Thread-19 (getsongs):
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.12/site-packages/t_modules/t_main.py", line 8866, in getsongs
    getsongs(index, item["id"], item["title"], inner=True, parent=item)
  File "/usr/lib/python3.12/site-packages/t_modules/t_main.py", line 8857, in getsongs
    if item["isDir"]:
       ~~~~^^^^^^^^^
KeyError: 'isDir'
    if item["isDir"]:
       ~~~~^^^^^^^^^
KeyError: 'isDir'
Exception in thread Thread-18 (getsongs):
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.12/site-packages/t_modules/t_main.py", line 8866, in getsongs
    getsongs(index, item["id"], item["title"], inner=True, parent=item)
  File "/usr/lib/python3.12/site-packages/t_modules/t_main.py", line 8857, in getsongs
    if item["isDir"]:
       ~~~~^^^^^^^^^
KeyError: 'isDir'
DEBUG: Position changed by playlist change
```

**Comment by C0rn3j** [comment]
I am still going to need the printed out `["subsonic-response"]` for that.

```python
print(d["subsonic-response"])
items = d["subsonic-response"]["directory"]["child"]
```

**Comment by C0rn3j** [comment]
@stkw0 could you grab the requested output or throw me some guest credentials to test with if your server is publicly available?

**Comment by stkw0** [comment]
Sorry. Yes, I attach the log with the output from subsonic-response + the exception. I was using version 8.0.1 of Tauon

**Comment by C0rn3j** [comment]
Can you try swapping  
`if item["isDir"]:`  
for  
`if "isDir" in item and item["isDir"]:`  
and see if that works?

This is what we're dealing with:

```json
{
    "openSubsonic": True,
    "serverVersion": "8",
    "status": "ok",
    "type": "lms",
    "version": "1.16.0",
    "directory": {
        "id": "dir-1295",
        "name": "A Ghost of Flare - Soulburner",
        "parent": "dir-1",
        "playCount": 0,
        "child": [
            {
                "album": "Soulburner",
                "albumId": "al-3334",
                "artist": "A Ghost of Flare",
                "artistId": "ar-706",
                "bitDepth": 16,
                "bitRate": 771,
                "channelCount": 2,
                "comment": "CRC : 73A3E843",
                "contentType": "audio/flac",
                "created": "2024-12-22T00:01:55.000",
                "displayAlbumArtist": "A Ghost of Flare",
                "displayArtist": "A Ghost of Flare",
                "duration": 83,
                "explicitStatus": "",
                "genre": "Metal",
                "id": "tr-9575",
                "mediaType": "song",
                "musicBrainzId": "",
                "path": "A Ghost of Flare - Soulburner/01 - Lost In The Fire.flac",
                "playCount": 1,
                "played": "2025-03-22T21:28:48.000",
                "samplingRate": 44100,
                "size": 8016750,
                "suffix": "flac",
                "title": "Lost In The Fire",
                "track": 1,
                "transcodedContentType": "audio/mpeg",
                "transcodedSuffix": "mp3",
                "type": "music",
                "year": 2019,
                "replayGain": {},
                "albumartists": [{"id": "ar-706", "name": "A Ghost of Flare"}],
                "artists": [{"id": "ar-706", "name": "A Ghost of Flare"}],
                "contributors": [],
                "genres": [{"name": "Metal"}],
                "moods": [],
            },
            {
                "album": "Soulburner",
                "albumId": "al-3334",
                "artist": "A Ghost of Flare",
                "artistId": "ar-706",
                "bitDepth": 16,
                "bitRate": 1080,
                "channelCount": 2,
                "comment": "CRC : 4EFC2DBA",
                "contentType": "audio/flac",
                "created": "2024-12-22T00:01:55.000",
                "displayAlbumArtist": "A Ghost of Flare",
                "displayArtist": "A Ghost of Flare",
                "duration": 251,
                "explicitStatus": "",
                "genre": "Metal",
                "id": "tr-9568",
                "mediaType": "song",
                "musicBrainzId": "",
                "path": "A Ghost of Flare - Soulburner/02 - Soulburner.flac",
                "playCount": 3,
                "played": "2024-12-01T08:29:00.000",
                "samplingRate": 44100,
                "size": 33888186,
                "suffix": "flac",
                "title": "Soulburner",
```

**Comment by stkw0** [comment]
Running the latest version from master branch  I seen this, which is probably unrelated.
```
2025-05-04 11:44:11 [ ERROR ] [  t_main  ] Index error (t_main.py:39991)
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/tauon/t_modules/t_main.py", line 39984, in <module>
    if save[183] is not None:
       ~~~~^^^^^
IndexError: list index out of range
```

Also I found a couple of errors like the next one. I would think that the problem may be that I didn't had installed the optional opencc package?
```
2025-05-04 11:45:30 [ ERROR ] [  t_main  ] Error reading Airsonic directory (t_main.py:18173)
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/tauon/t_modules/t_main.py", line 18166, in getsongs
    d = self.r("getMusicDirectory", p={"id": folder_id})
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/tauon/t_modules/t_main.py", line 18079, in r
    d = json.loads(response.text)
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/decoder.py", line 338, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/decoder.py", line 354, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Invalid control character at: line 1 column 2627 (char 2626)
```

The songs play correctly and seems overall is working fine :) 
Another minor problem is that the cover doesn't loads, but it loads when playing the same song offline.
```
2025-05-04 11:48:06 [ ERROR ] [  t_dbus  ] Thumbnail error (t_dbus.py:426)
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/tauon/t_modules/t_dbus.py", line 422, in update
    i_path = tauon.thumb_tracks.path(track)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/tauon/t_modules/t_main.py", line 5378, in path
    with Image.open(source_image) as im:
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/PIL/Image.py", line 3572, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x77327cd2fc90>
2025-05-04 11:48:06 [ ERROR ] [  t_main  ] Image load error (t_main.py:21040)
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/tauon/t_modules/t_main.py", line 20788, in display
    im = Image.open(source_image)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/PIL/Image.py", line 3572, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file <_io.BufferedReader name='/home/david/.cache/TauonMusicBox/network/0d19b7da519c'>
2025-05-04 11:48:06 [ ERROR ] [  t_main  ] -- Associated track: BUGY CRAXONE/BUGY CRAXONE_-_BUGY CRAXONE/BUGY CRAXONE (2005.11.23)/10 CITY GIRL.mp3 (t_main.py:21041)
```

**Comment by stkw0** [comment]
btw, if it would be easier for testing, I can provide an account in the web server I have running. If you would like, please share an email or a Telegram or IRC nickname where I can reach you.

**Comment by C0rn3j** [comment]
> if it would be easier for testing, I can provide an account in the web server I have running

Possibly, my tg nickname is the same as here.

The first error is known but can be ignored, it only happens once on db upgrade and doesn't hurt anything, I'll try to remember to fix it later.

**Comment by stkw0** [comment]
I just sent the details on Telegram.

Also, seems that if one tries to import the playlist but the password is wrong, the error is not properly handled and when trying again with the correct password there is a message saying that "It's already scanning"

**Comment by C0rn3j** [comment]
So this thread covers many issues

1. Crash on failed login - fixed - now shows the error to the user
2. Fail on import - caused by broken server sending JSON with raw control characters - you should report that to your server, added a detect and workaround for it
3. Fail to load images -  we're sending this text down the way in Tauon as an image - yet to fix.

```
{"subsonic-response":{"openSubsonic":true,"serverVersion":"8","status":"failed","type":"lms","version":"1.16.0","error":{"code":10,"message":"Required parameter 'id' is missing."}}}
```
