### ISSUE TITLE
Accessing Jellyfin library, but forever stuck at that point

### ISSUE THREAD

**Issue by dln949** [Taiko2k/Tauon#1222]
Flatpak Tauon 7.8.3 on Ubuntu 22.04, gnome shell 42.9, wayland.  

I set up the Jellyfin server on a different Ubuntu machine, but on the same LAN.  Entering the Jellyfin credentials into the Jellyfin account in Tauon and then testing the connection works fine.  Then I click on import the music, and I see the message that Tauon is "Accessing JELLYFIN library...."  But, it is forever stuck at that stage, no music tracks are ever imported.  (Importing the Airsonic library from the same computer that Jellyfin is on worked just fine.)

**Comment by Taiko2k** [comment]
Could you launch Tauon from terminal (using `flatpak run com.github.taiko2k.tauonmb`), try import again and see if there are any obvious errors printed to terminal?

**Comment by dln949** [comment]
> Could you launch Tauon from terminal (using `flatpak run com.github.taiko2k.tauonmb`), try import again and see if there are any obvious errors printed to terminal?

Here is the terminal output you asked for (I don't know how to interpret it):  

`main1@system1:~$ flatpak run com.github.taiko2k.tauonmb
Tauon v7.8.3
Copyright 2015-2023 Taiko2k captain.gxj@gmail.com

2021
Window size: [1920, 1080]
Detected running as Flatpak
Installed as Flatpak
User files location: /home/main1/.var/app/com.github.taiko2k.tauonmb/data/TauonMusicBox
Found XDG-Downloads: /home/main1/Downloads
Found XDG-Music: /home/main1/Music
Install directory: /app/bin
Database loaded in 0.182 seconds.
Error loading xcursor
Scanning for chromecasts...
Start controller server
Start PHAzOR backend...
Using SDL version: 2.28.5
Load Bio Data
Applying theme: Turbo
Exit Phazor
Message: Connection and authorisation successful
Prepare for Jellyfin library import...
Get items...
Grrr why this happen, stupid bug
Grrr why this happen, stupid bug
Grrr why this happen, stupid bug
Grrr why this happen, stupid bug
Connection successful, storing items...
Exception in thread Thread-15 (ingest_library):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/app/bin/t_modules/t_jellyfin.py", line 439, in ingest_library
    nt.size = track.get("MediaSources")[0]["Size"]
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'Size'`

**Comment by Taiko2k** [comment]
OK ive committed a possible fix for this. Will be included in next release.

**Comment by C0rn3j** [comment]
There are a lot of `requests` that do not have a timeout and can thus hang indefinitely, which could be causing hangs.

I've been touching up the modules and fixing the same problem elsewhere as I go, I plan to get to jellyfin too eventually,

**Comment by chris246** [comment]
Are there plans for the next release?

It would be nice to have a fixed version ;)

**Comment by C0rn3j** [comment]
It's not immediately incoming, to my knowledge.

The [upcoming 7.9.0](https://github.com/Taiko2k/Tauon/blob/master/CHANGELOG.md#v790) has huge changes all around, so it's best it gets tested more than usual, I was still fixing crashes stemming from the changes 2 days ago. 

You can help speed things up by running the git version and reporting any issues, just make sure to backup your current userdata if you care about it.  

It shouldn't eat your data, but just in case.

**Comment by C0rn3j** [comment]
Tauon now has prebuilt images for macOS, Windows and Linux per commit, so you can easily test if your issue is fixed.

Tap the checkmark icon in this commit as the PR enablign Windows and Linux isn't merged yet - https://github.com/Taiko2k/Tauon/pull/1354/commits/56f6d4beeb3d8c885bab609a3d4ed97a94dc020c

**Comment by C0rn3j** [comment]
Closing since it should be either fixed by Taiko's fixes, my fixes or a combination of both.

If you still have the issue on current master, comment and we'll reopen.
