### ISSUE TITLE
7.9.0 - "Add to queue" crashes Tauon

### ISSUE THREAD

**Issue by Lorsoen** [Taiko2k/Tauon#1333]
As in the title. Returning error :

```bash
Traceback (most recent call last):
  File "/usr/bin/tauonmb", line 5, in <module>
    from tauon.__main__ import main
  File "/usr/lib/python3.12/site-packages/tauon/__main__.py", line 478, in <module>
    from tauon.t_modules import t_main
  File "/usr/lib/python3.12/site-packages/tauon/t_modules/t_main.py", line 46744, in <module>
    queue_box.draw(0, gui.panelY + pl_box_h, gui.lspw, full - pl_box_h)
  File "/usr/lib/python3.12/site-packages/tauon/t_modules/t_main.py", line 39446, in draw
    self.draw_card(x, y, w, h, yy, track, fq[i], db)
  File "/usr/lib/python3.12/site-packages/tauon/t_modules/t_main.py", line 39204, in draw_card
    if fqo[3] == 0:
       ~~~^^^
TypeError: 'TauonQueueItem' object is not subscriptable
```

**Comment by C0rn3j** [comment]
Missed that one, thanks for the report, I'll send a fix along with some
other fixes in the near time unless someone beats me to it.

If you want to fix it locally, you can read the class description for
TauonQueueItem in I believe t_extra.py to see what to replace the [3] with,
in the fqo[x] instances
