### ISSUE TITLE
Tauon will immediatly crash when trying to show a file with invalid encoding filename

### ISSUE THREAD

**Issue by awsms** [Taiko2k/Tauon#552]
```python
Traceback (most recent call last):
  File "./tauon.py", line 186, in <module>
    exec(main)
  File "./t_modules/t_main.py", line 42018, in <module>
    playlist_render.full_render()
  File "./t_modules/t_main.py", line 32184, in full_render
    ddt.text((run + 6 * gui.scale, y + y_off),
  File "/home/user/TauonMusicBox/t_modules/t_draw.py", line 824, in text
    return self.__draw_text_cairo(location, text, colour, font, max_w, bg, align)
  File "/home/user/TauonMusicBox/t_modules/t_draw.py", line 548, in __draw_text_cairo
    w, h = self.get_text_wh(text, font, max_x, wrap)
  File "/home/user/TauonMusicBox/t_modules/t_draw.py", line 423, in get_text_wh
    self.layout.set_text(text, -1)
  File "/home/user/.local/lib/python3.8/site-packages/gi/overrides/Pango.py", line 54, in set_text
    super(Layout, self).set_text(text, length)
UnicodeEncodeError: 'utf-8' codec can't encode character '\udce9' in position 131: surrogates not allowed
```

In my terminal, the filename is shown as '10. Kaaris - H'$'\351''mophiles.flac' (it's supposed to be '10. Kaaris - Hémophiles.flac')
This cd was ripped on windows, which explains the sh*tty character encoding

**Comment by Taiko2k** [comment]
Not sure how to approach fixing this. In the mean time I suggest just renaming those files.

**Comment by Taiko2k** [comment]
Okay I've committed a fix now that should probably fix it

**Comment by C0rn3j** [comment]
@Taiko2k I suppose this can be closed?
