### ISSUE TITLE
macOS support (experimental)

### ISSUE THREAD

**Issue by Taiko2k** [Taiko2k/Tauon#577]
### Welcome to Tauon Music Box support for macOS.

Note that this is experimental and there are some caveats:

### Caveats:
 - No fancy precompiled `.dmg`. You’ll need to build from source.
 - No desktop panel control. (Get in touch if you're familiar with mac development and think you can help with this.)
 - No output device selection, only default output.
 - More likely to crash than on Linux

### How to build and install:

The build instructions below will give you a `.app` so once done you can use it like a normal desktop app.

1. Install [Homebrew](https://brew.sh)
2. Install main dependencies `brew install pygobject3 gtk+3 python ffmpeg pyinstaller libao sdl2 sdl2_image flac mpg123 opusfile libopenmpt libsamplerate libvorbis librsvg wavpack`
3. Clone Tauon repo `git clone --recursive https://github.com/Taiko2k/TauonMusicBox.git`
4. `cd TauonMusicBox`
5. Install python dependencies `pip3 install -r requirements.txt`
6. Run `bash compile-phazor.sh` (some warnings in the output are ok, as long as there was no error)
7. You can run using `python3 tauon.py`
8. ~~Build .app by running `pyinstaller mac.spec --clean --noconfirm`~~ Package script currently broken, have to run from terminal. 

That should give you a (hopefully working) .app in the `TauonMusicBox/dist` directory that you can run as is or move to your applications folder.

Note that the script currently has a limitation in that the built .app is still *linked* to the homebrew prefix, so removing or updating the prefix may cause the .app to stop working.

Note that user data is kept in `~/.local/share/TauonMusicBox`

**Comment by Taiko2k** [comment]
@Movisivi Sure, you can see the full list of shortcuts here  https://github.com/Taiko2k/TauonMusicBox/blob/master/input.txt. So, add to queue is Alt-Q.

**Comment by Taiko2k** [comment]
@Movisivi Yes that file will be available to edit in the user data folder. You will be able to find that from Tauon by going MENU > Settings... > Open data folder.

> is there a pane (similar to Musicbee) that shows the upcoming tracks so I can sort them after I queue them?

This can be done using the mouse. Open the panel by clicking the topmost left button in the window.

You should probably just try the app out to see if you like it. Tauon is quite a unique music player.

**Comment by jkglenn** [comment]
I followed your instructions, but didn't get a .app. Instead I ended up with a Unix executable that doesn't launch the app.
Too bad, Tauon is one of the apps I miss the most from Linux (I'm forced to use a Macbook for work). Being able to do a clean install via `brew cask` would be ideal.

**Comment by fangxx3863** [comment]
I succeeded  
it also need to `brew install librsvg` and edit mac.spec modify `hiddenimports=[],` to `hiddenimports=['sdl2', 'pylast'],`  
![image](https://user-images.githubusercontent.com/48589001/147389560-ad47a83d-1fa9-437c-af1d-411018c7b7cb.png)

**Comment by Taiko2k** [comment]
> I succeeded it also need to `brew install librsvg` and edit mac.spec modify `hiddenimports=[],` to `hiddenimports=['sdl2', 'pylast'],`

Neat. Ive now updated the instructions and script with the modifications you made.

**Comment by jkglenn** [comment]
I tried again with the new instructions, now on Monterey (12.1). Got through the build process without errors, other than pip reminding me about the deprecation of distutils. I tried to run the resulting TMB executable and got the following error:

`[23812] Error loading Python lib '/Users/jkglenn/src/TauonMusicBox/build/mac/Python': dlopen: dlopen(/Users/jkglenn/src/TauonMusicBox/build/mac/Python, 0x000A): tried: '/Users/jkglenn/src/TauonMusicBox/build/mac/Python' (no such file), '/usr/local/lib/Python' (no such file), '/usr/lib/Python' (no such file)`

I currently have a homebrew-installed Python which is symlinked to `/usr/local/opt/python@3.9/libexec/bin/python`.

**Comment by fangxx3863** [comment]
> I tried again with the new instructions, now on Monterey (12.1). Got through the build process without errors, other than pip reminding me about the deprecation of distutils. I tried to run the resulting TMB executable and got the following error:
> 
> `[23812] Error loading Python lib '/Users/jkglenn/src/TauonMusicBox/build/mac/Python': dlopen: dlopen(/Users/jkglenn/src/TauonMusicBox/build/mac/Python, 0x000A): tried: '/Users/jkglenn/src/TauonMusicBox/build/mac/Python' (no such file), '/usr/local/lib/Python' (no such file), '/usr/lib/Python' (no such file)`
> 
> I currently have a homebrew-installed Python which is symlinked to `/usr/local/opt/python@3.9/libexec/bin/python`.

I think you can try a virtual environment  
Use anaconda or python venv  
https://docs.python.org/3/library/venv.html  
Also note that the python version cannot be 3.10.0  
Because pyinstaller cannot run normally under version 3.10.0  
https://github.com/pyinstaller/pyinstaller/issues/5693

**Comment by jkglenn** [comment]
Thank you very much for the suggestions. I did finally locate the .app under `TauonMusicBox/dist/TauonMusicBox.app,` but it just fails silently when I launch it. Setting up a venv to run a music player app is a bridge too far IMO... so it's back to iTunes.

**Comment by a-hurst** [comment]
>> todo: unlink app from homebrew prefix, it can break on homebrew update. (SDL2 libs causing the issue?)

@Taiko2k You might have better luck adding the `pysdl2-dll` Python package as a dependency for macOS, it contains the latest official signed SDL2 and Mixer binaries from libSDL.org in a Python wheel that PySDL2 can automatically find and use! It's the current recommended way to use PySDL2 on all major platforms, since installing the SDL2 binaries system-wide on Windows is a big pain and so many Linux distros bundle very out-of-date SDL/ttf/mixer/image versions.

Also, if you have any other questions/comments/complaints/feature requests for the PySDL2 project, please let me know! I'm the current maintainer and want to be sure I'm doing good outreach for projects that use it. 🙂

**Comment by Taiko2k** [comment]
@a-hurst Indeed I noticed `pysdl2-dll`, I was going to give it a try but I'm waiting on Apple Silicon support.

Thanks for working on PySDL2, its a great library and I haven't had any issues with it.

**Comment by fyrefiend** [comment]
I'd absolutely love a precompiled Tauon pkg, app, or cask for Mac. 

Unfortunately I'm having the same issue as @cschx. 

I'm running macOS 12.3.1 x86_64
If there is any info I can add please let me know and I'll happily supply it.

**Comment by Taiko2k** [comment]
@fyrefiend If you run the built app from terminal it might give us a more helpful error message which we could take a look at. From the project root try run: 

> "dist/TauonMusicBox.app/Contents/MacOS/Tauon Music Box"

**Comment by fyrefiend** [comment]
> 

Gladly. Sorry, I should have done that to begin with. 

`Traceback (most recent call last):
  File "tauon.py", line 8, in <module>
    from sdl2 import *
ModuleNotFoundError: No module named 'sdl2'
[27344] Failed to execute script 'tauon' due to unhandled exception: No module named 'sdl2'
[27344] Traceback:
Traceback (most recent call last):
  File "tauon.py", line 8, in <module>
    from sdl2 import *
ModuleNotFoundError: No module named 'sdl2'`

However it is installed as 
'python3 tauon.py' works fine

**Comment by Taiko2k** [comment]
Could try see if pysdl2-dll helps.

Try `pip install pysdl2-dll`, then hmm, might need to edit mac.spec file and add `sdl2dll` as a "hiddenimports" line.

**Comment by fyrefiend** [comment]
Thank you for the reply. I've installed pysld12-dkk and added it to the mac.spec file but still getting:

`Traceback (most recent call last):
  File "tauon.py", line 8, in <module>
    from sdl2 import *
ModuleNotFoundError: No module named 'sdl2'
[32126] Failed to execute script 'tauon' due to unhandled exception: No module named 'sdl2'
[32126] Traceback:
Traceback (most recent call last):
  File "tauon.py", line 8, in <module>
    from sdl2 import *
ModuleNotFoundError: No module named 'sdl2'
`

Attached in the warn-mac.txt that pyinstaller generated. It's saying sdl2 is not installed but if I can run the python file itself fine so it's obviously installed.
[warn-mac.txt](https://github.com/Taiko2k/TauonMusicBox/files/8791543/warn-mac.txt)

**Comment by a-hurst** [comment]
@fyrefiend Hi there, PySDL2 maintainer here: looks like you've installed `pysdl2-dll` (the package with the pre-compiled SDL2 binaries for your OS) but not `pysdl2` itself (the Python bindings for SDL2 and its addon libraries). Try running `pip install pysdl2` and try again!

Also note that the latest pysdl2-dll binaries aren't yet fully natively compatible with Apple Silicon: since pysdl2-dll just bundles the official code-signed libSDL binaries for Windows and macOS, I've been waiting patiently for the SDL people to release universal binaries of `SDL2_image` and `SDL2_mixer` so I can update `pysdl2-dll` accordingly. Luckily it looks like new releases of both are imminent, so you shouldn't have to wait long.

**Comment by fyrefiend** [comment]
@a-hurst Tried including both in `mac.spec` but still getting the same error. Thank you though

**Comment by boromil** [comment]
> bash ./compile-phazor.sh

complains about missing wavpack pkg

> brew install wavpack

fixes that, but then I get:

> clang: error: no such file or directory: 'src/phazor/kissfft/kiss_fftr.c'
clang: error: no such file or directory: 'src/phazor/kissfft/kiss_fft.c'

removing references to these (bad idea, I know) from the build script, produces another error:

> src/phazor/phazor.c:41:10: fatal error: 'miniaudio/miniaudio.h' file not found

dl the header file and placing it in src/phazor

> mkdir src/phazor/miniaudio
cd src/phazor/miniaudio
curl -O https://raw.githubusercontent.com/mackron/miniaudio/master/miniaudio.h

results in:

> ...
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreAudio.framework/Headers/AudioHardwareBase.h:208:5: note: 'kAudioObjectPropertyElementMaster' has been explicitly marked deprecated here
    kAudioObjectPropertyElementMaster API_DEPRECATED_WITH_REPLACEMENT("kAudioObjectPropertyElementMain", macos(10.0, 12.0), ios(2.0, 15.0), watchos(1.0, 8.0), tvos(9.0, 15.0)) = kAudioObjectPropertyElementMain
    ^
src/phazor/phazor.c:52:10: fatal error: 'kissfft/kiss_fftr.h' file not found
#include "kissfft/kiss_fftr.h"

So the build process seems broken for now ;/

**Comment by Taiko2k** [comment]
@boromil yeah the instructions were a little out of date. Ive updated them now, note the change to step 3.

Though the built package is currently crashes it seems, so this all might not be very useful.

**Comment by Taiko2k** [comment]
Ive committed a fix for the above compile issue now.

**Comment by melvyn2** [comment]
Worked with a single typo in step 6: `phazor` not `phasor`
Also the pyinstaller step does work, I get a standalone .app
Thanks!

**Comment by Looooopy** [comment]
i'm getting these errors when i try to install it on a macos ...

```
src/phazor/phazor.c:1082:9: warning: unused variable 'b' [-Wunused-variable]
    int b = get_audio(frameCount * 2, pOutput);
        ^
src/phazor/phazor.c:1179:9: error: implicit declaration of function 'decode_seek' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        decode_seek(position_count / current_sample_rate * 1000, sample_rate_src);
        ^
src/phazor/phazor.c:1198:6: error: conflicting types for 'decode_seek'
void decode_seek(int abs_ms, int sample_rate) {
     ^
src/phazor/phazor.c:1179:9: note: previous implicit declaration is here
        decode_seek(position_count / current_sample_rate * 1000, sample_rate_src);
```

But my arch linux install is rocking hard :)

**Comment by Looooopy** [comment]
I inserted a predeclaration up on top o the file and got it to work

inserted this at line 70
`void decode_seek(int abs_ms, int sample_rate);`

**Comment by earnost** [comment]
I feel like I'm so close. Worked out several issues but now stuck on this. When I run bash compile-phazor.sh I get:

Package libpipewire-0.3 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libpipewire-0.3.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libpipewire-0.3' found
src/phazor/phazor.c:69:10: fatal error: 'opusfile.h' file not found
#include "opusfile.h"
         ^~~~~~~~~~~~

I'm on a 2019 Intel Macbook Pro. Searched the web but couldn't figure out how to get this libpipewire-0.3. Any help is appreciated as I'm fairly new at this. I think that's my last issue and then it should run. Thanks for your help.

**Comment by Taiko2k** [comment]
@earnost The script broke for non Linux platforms, I've committed a possible fix, try pull and try again.

**Comment by earnost** [comment]
Thank you, what's the possible fix? I don't see it

**Comment by Taiko2k** [comment]
https://github.com/Taiko2k/Tauon/commit/361eb16f92d3984d29726545ccd5b37fa6fcaca5

**Comment by dmt-hub** [comment]
When trying to run python3 tauon.py i get this error: 

/usr/local/bin/python3 tauon.py
Traceback (most recent call last):
  File "/Users/username/TauonMusicBox/tauon.py", line 25, in <module>
    from gi.repository import GLib
ModuleNotFoundError: No module named 'gi'

Any ideas on how to solve this?

**Comment by C0rn3j** [comment]
Now *with* the prebuilt DMG - https://github.com/Taiko2k/Tauon/pull/1348!

But it seems broken for now, and I don't have a Mac to test with, so help welcome, feel free to tag me on the Discord or just keep it here.

**Comment by thelazyoxymoron** [comment]
Hi @C0rn3j, I tried running the DMG generated from the latest CI run [Try 24.10](https://github.com/C0rn3j/Tauon/actions/runs/12403428239) and faced this error:

```
UserWarning: Using SDL2 binaries from pysdl2-dll 2.30.10
Traceback (most recent call last):
  File "sdl2/sdlimage.py", line 33, in <module>
  File "sdl2/dll.py", line 253, in __init__
RuntimeError: could not find any library for SDL2_image (PYSDL2_DLL_PATH: /Applications/TauonMusicBox.app/Contents/Frameworks/sdl2dll/dll)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tauon/__main__.py", line 63, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "sdl2/sdlimage.py", line 37, in <module>
ImportError: could not find any library for SDL2_image (PYSDL2_DLL_PATH: /Applications/TauonMusicBox.app/Contents/Frameworks/sdl2dll/dll)
[PYI-84800:ERROR] Failed to execute script '__main__' due to unhandled exception: could not find any library for SDL2_image (PYSDL2_DLL_PATH: /Applications/TauonMusicBox.app/Contents/Frameworks/sdl2dll/dll)
[PYI-84800:ERROR] Traceback:
Traceback (most recent call last):
  File "sdl2/sdlimage.py", line 33, in <module>
  File "sdl2/dll.py", line 253, in __init__
RuntimeError: could not find any library for SDL2_image (PYSDL2_DLL_PATH: /Applications/TauonMusicBox.app/Contents/Frameworks/sdl2dll/dll)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tauon/__main__.py", line 63, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "sdl2/sdlimage.py", line 37, in <module>
ImportError: could not find any library for SDL2_image (PYSDL2_DLL_PATH: /Applications/TauonMusicBox.app/Contents/Frameworks/sdl2dll/dll)
```

**Comment by C0rn3j** [comment]
Did you export PYSDL2_DLL_PATH to be pointing where it's pointing yourself?

i.e.

```
export PYSDL2_DLL_PATH=/Applications/TauonMusicBox.app/Contents/Frameworks/sdl2dll/dll
```

Can also try DYLD_LIBRARY_PATH for when later things start failing after you get past SDL, and let me know if that helps any.
```
export DYLD_LIBRARY_PATH=/Volumes/TauonMusicBox/TauonMusicBox.app/Contents/Frameworks
```


The issue seems to be that pyinstaller *helpfully* sanitized the dot, I'll see what voodoo I have to commit to fix that...

 I see why Taiko hates build systems now.
```
sdl2dll/dll/SDL2_image.framework/Versions/A/Frameworks/webp.framework/webp
sdl2dll/dll/SDL2_image__dot__framework/Versions/A/Frameworks/webp.framework/webp
```

**Comment by C0rn3j** [comment]
@thelazyoxymoron the pysdl issue should now be resolved in the latest commit - https://github.com/Taiko2k/Tauon/actions/runs/12421344952

**Comment by Taiko2k** [comment]
Got `TypeError: cannot create instance of abstract (non-instantiable) type `GError'`` and  `Class is implemented in both, One of the two will be used. Which one is undefined`. 

Deleting my `/opt/homebrew` folder works around that.

Now I get

```
UserWarning: Using SDL2 binaries from pysdl2-dll 2.30.10
2024-12-20 11:21:40 [ INFO  ] [ __main__ ] Tauon v7.9.0
2024-12-20 11:21:40 [ INFO  ] [ __main__ ] Copyright 2015-2024 Taiko2k captain.gxj@gmail.com

2024-12-20 11:21:40 [WARNING] [  t_draw  ] Unable to import jxlpy, JPEG XL support will be disabled. (t_draw.py:67)
2024-12-20 11:21:40 [WARNING] [  t_main  ] Unable to import jxlpy, JPEG XL support will be disabled. (t_main.py:358)
2024-12-20 11:21:40 [ INFO  ] [  t_main  ] Window size: [2626, 1286]
2024-12-20 11:21:40 [ INFO  ] [  t_main  ] Running from installed location
2024-12-20 11:21:40 [ INFO  ] [  t_main  ] User files location: /Users/kai/.local/share/TauonMusicBox
2024-12-20 11:21:40 [ INFO  ] [  t_main  ] Install directory:         /Applications/TauonMusicBox.app/Contents/Frameworks
2024-12-20 11:21:40 [ INFO  ] [  t_main  ] Config directory:          /Users/kai/.local/share/TauonMusicBox
2024-12-20 11:21:40 [ INFO  ] [  t_main  ] Cache directory:           /Users/kai/.cache/TauonMusicBox
2024-12-20 11:21:40 [ INFO  ] [  t_main  ] Home directory:            /Users/kai
2024-12-20 11:21:40 [ INFO  ] [  t_main  ] Music directory:           /Users/kai/Music
2024-12-20 11:21:40 [ INFO  ] [  t_main  ] Download directory:        /Users/kai/Downloads
2024-12-20 11:21:40 [ INFO  ] [  t_main  ] Asset directory:           /Applications/TauonMusicBox.app/Contents/Frameworks/assets
2024-12-20 11:21:40 [ INFO  ] [  t_main  ] Locale directory:          /Applications/TauonMusicBox.app/Contents/Frameworks/locale
2024-12-20 11:21:40 [WARNING] [  t_main  ] Loaded older DB version: 66 (t_main.py:3137)
2024-12-20 11:21:40 [ ERROR ] [  t_main  ] Index error (t_main.py:3508)
Traceback (most recent call last):
  File "tauon/t_modules/t_main.py", line 3491, in <module>
IndexError: list index out of range
2024-12-20 11:21:40 [ INFO  ] [  t_main  ] Database loaded in 0.128 seconds.
2024-12-20 11:21:40 [WARNING] [  t_main  ] Current DB version 66 was lower than latest 69, running migrations! (t_main.py:3572)
2024-12-20 11:21:40 [WARNING] [t_db_migrate] Running migrations as DB version was 66! (t_db_migrate.py:55)
2024-12-20 11:21:40 [ INFO  ] [t_db_migrate] Updating database to version 67
2024-12-20 11:21:40 [ INFO  ] [t_db_migrate] Updating database to version 68
2024-12-20 11:21:40 [ INFO  ] [t_db_migrate] Updating database to version 69
2024-12-20 11:21:40 [ INFO  ] [  t_main  ] Force rerender icons
Traceback (most recent call last):
  File "tauon/__main__.py", line 443, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "tauon/t_modules/t_main.py", line 4368, in <module>
  File "tauon/t_modules/t_main.py", line 4338, in scale_assets
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "tauon/t_modules/t_svgout.py", line 27, in <module>
  File "gi/__init__.py", line 122, in require_version
ValueError: Namespace Rsvg not available
[PYI-25388:ERROR] Failed to execute script '__main__' due to unhandled exception: Namespace Rsvg not available
[PYI-25388:ERROR] Traceback:
Traceback (most recent call last):
  File "tauon/__main__.py", line 443, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "tauon/t_modules/t_main.py", line 4368, in <module>
  File "tauon/t_modules/t_main.py", line 4338, in scale_assets
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "tauon/t_modules/t_svgout.py", line 27, in <module>
  File "gi/__init__.py", line 122, in require_version
ValueError: Namespace Rsvg not available
```

**Comment by C0rn3j** [comment]
The v66 migration is bothersome, I presume that's why the list index error popped up.

librsvg issue is known to me and you can work around it by `brew install librsvg` but I am not sure how to correctly package rsvg through pyinstaller at the moment.

> Class is implemented in both, One of the two will be used. Which one is undefined

Got a bunch of those, still yet to figure out how to specify to builtin one but I haven't looked too hard.

**Comment by Taiko2k** [comment]
> I presume that's why the list index error popped up.

This is often normal if a new entry has been added, the length of the old list is then shorter than the new one, it will error out but that's intended. (Don't ask me who designed this 😄)

**Comment by C0rn3j** [comment]
Rsvg issue is fixed on latest commits, was an upstream issue in pyinstaller - https://github.com/pyinstaller/pyinstaller/pull/8940

We'll just have to carry an extra hook for Rsvg til a new release ships.

**Comment by thelazyoxymoron** [comment]
I got this error as well:
```
bjc[20117]: Class GNotificationCenterDelegate is implemented in both /Applications/TauonMusicBox.app/Contents/Frameworks/libgio-2.0.0.dylib (0x1192e46c0) and /opt/homebrew/Cellar/glib/2.82.4/lib/libgio-2.0.0.dylib (0x11fb40648). One of the two will be used. Which one is undefined.
```

I deleted the one defined in `/Contents/Frameworks/` and re-ran and then got this error:
```
** (process:42991): WARNING **: 16:02:15.735: Failed to load shared library '@loader_path/libgio-2.0.0.dylib' referenced by the typelib: dlopen(@loader_path/libgio-2.0.0.dylib, 0x0009): tried: '/Applications/TauonMusicBox.app/Contents/Frameworks/libgio-2.0.0.dylib' (no such file)
Traceback (most recent call last):
  File "tauon/__main__.py", line 436, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "tauon/t_modules/t_main.py", line 262, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "tauon/t_modules/t_draw.py", line 85, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 921, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 813, in module_from_spec
  File "gi/importer.py", line 146, in create_module
  File "importlib/__init__.py", line 88, in import_module
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 921, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 813, in module_from_spec
  File "gi/importer.py", line 147, in create_module
  File "gi/overrides/__init__.py", line 112, in load_overrides
  File "importlib/__init__.py", line 88, in import_module
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "gi/overrides/Gio.py", line 37, in <module>
  File "gi/module.py", line 177, in __getattr__
  File "gi/module.py", line 99, in get_interfaces_for_object
  File "gi/overrides/__init__.py", line 31, in __getattr__
  File "gi/module.py", line 217, in __getattr__
  File "gi/types.py", line 247, in __init__
TypeError: must be an interface
```

This is a bit weird. It looks like it was trying to load `/Applications/TauonMusicBox.app/Contents/Frameworks/libgio-2.0.0.dylib` in the first place, so that earlier ambiguous file error should not have come. I don't want to delete my system `libgio` as another application might be dependent on it.

**Comment by C0rn3j** [comment]
@thelazyoxymoron can you make sure you're running on currently latest build - which is this at the moment - https://github.com/C0rn3j/Tauon/actions/runs/12428672958 and you can reproduce it after running `brew update && brew upgrade`?

If so please post the log in full

**Comment by thelazyoxymoron** [comment]
Awesome, I was able to make it run with the latest action run!

<img width="1489" alt="Screenshot 2024-12-20 at 4 29 13 PM" src="https://github.com/user-attachments/assets/175a12fa-0abf-455f-8ade-b2c2565141b0" />

**Comment by C0rn3j** [comment]
@Taiko2k I think now that we have official DMGs, it's best to close this and open separate issues for anything specific to macOS that remains.
