### ISSUE TITLE
Exception in thread - Null bytes in flac

### ISSUE THREAD

**Issue by awsms** [Taiko2k/Tauon#597]
```python
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ash/Appz/TauonMusicBox/t_modules/t_main.py", line 4721, in notify_update_fire
    self.mpris.update()
  File "/home/ash/Appz/TauonMusicBox/t_modules/t_dbus.py", line 448, in update
    self.PropertiesChanged('org.mpris.MediaPlayer2.Player', changed, [])
  File "/home/ash/.local/lib/python3.8/site-packages/dbus/decorators.py", line 325, in emit_signal
    message.append(signature=signature, *args)
ValueError: embedded null byte
```
Having this error when launching Tauon. I can play a song by double-clicking, then tauon immediatly freezes (the track is played untill the end).

**Comment by C0rn3j** [comment]
@awsms Is it still the case today?

**Comment by C0rn3j** [comment]
Closing since it's been 4 years without a response, if you can still repro it on current master, do ping back (ideally on Discord so we can deal with the files) and we'll reopen it.
