### ISSUE TITLE
Tauon v7.2.0 crashes on startup

### ISSUE THREAD

**Issue by Scotty-Trees** [Taiko2k/Tauon#750]
Greetings,

Congrats on a new release btw! Now I'm on a recently newly installed EndeavourOS Gnome setup on my Acer laptop, Tauon was installed from your AUR package a couple days ago by me and just now I updated to v7.2.0, but when I try to launch Tauon, it instantly crashes. Here's the error that shows when I run it from the terminal:

```
[scott@endeavourOS ~]$ tauon
No previous window state
Tauon Music Box v7.2.0
Copyright 2015-2022 Taiko2k captain.gxj@gmail.com

Window size: [1120, 600]
GTK theme is: yaru-blue-dark
Running from installed location
User files location: /home/scott/.local/share/TauonMusicBox
Clearing old cache directory
/home/scott/.cache/TauonMusicBox
Found XDG-Downloads: /home/scott/Downloads
Found XDG-Music: /home/scott/Music
Install directory: /opt/tauon-music-box
Traceback (most recent call last):
  File "/opt/tauon-music-box/tauon.py", line 248, in <module>
    exec(main)
  File "/opt/tauon-music-box/t_modules/t_main.py", line 666, in <module>
    import pylast
  File "/usr/lib/python3.10/site-packages/pylast/__init__.py", line 37, in <module>
    import httpx
ModuleNotFoundError: No module named 'httpx'
[scott@endeavourOS ~]$ 
```

If you need anything else from me, please let me know, for now if it is helpful, I'll leave my system information if you need:

```
[scott@endeavourOS ~]$ inxi -Fxxxza
System:
  Kernel: 5.17.7-arch1-1 arch: x86_64 bits: 64 compiler: gcc v: 12.1.0
    parameters: BOOT_IMAGE=/boot/vmlinuz-linux
    root=UUID=8fa8b163-e92a-4c63-b3b2-4e95cb5cbf5b rw
    resume=UUID=07eb68e8-871d-41a4-9496-89309eef9887 quiet loglevel=3
    nowatchdog nvme_load=YES nvidia-drm.modeset=1
  Desktop: GNOME v: 42.1 tk: GTK v: 3.24.33 wm: gnome-shell dm: GDM v: 42.0
    Distro: EndeavourOS base: Arch Linux
Machine:
  Type: Laptop System: Acer product: Aspire E5-576G v: V1.32
    serial: <superuser required>
  Mobo: KBL model: Ironman_SK v: V1.32 serial: <superuser required>
    UEFI: Insyde v: 1.32 date: 10/24/2017
Battery:
  ID-1: BAT1 charge: 12.6 Wh (100.0%) condition: 12.6/62.2 Wh (20.2%)
    volts: 12.6 min: 11.1 model: PANASONIC AS16B5J type: Li-ion
    serial: <filter> status: full
CPU:
  Info: model: Intel Core i5-8250U bits: 64 type: MT MCP arch: Coffee Lake
    family: 6 model-id: 0x8E (142) stepping: 0xA (10) microcode: 0xF0
  Topology: cpus: 1x cores: 4 tpc: 2 threads: 8 smt: enabled cache:
    L1: 256 KiB desc: d-4x32 KiB; i-4x32 KiB L2: 1024 KiB desc: 4x256 KiB
    L3: 6 MiB desc: 1x6 MiB
  Speed (MHz): avg: 3400 min/max: 400/3400 scaling: driver: intel_pstate
    governor: powersave cores: 1: 3400 2: 3400 3: 3400 4: 3400 5: 3400 6: 3400
    7: 3400 8: 3400 bogomips: 28808
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx
  Vulnerabilities:
  Type: itlb_multihit status: KVM: VMX disabled
  Type: l1tf
    mitigation: PTE Inversion; VMX: conditional cache flushes, SMT vulnerable
  Type: mds mitigation: Clear CPU buffers; SMT vulnerable
  Type: meltdown mitigation: PTI
  Type: spec_store_bypass
    mitigation: Speculative Store Bypass disabled via prctl
  Type: spectre_v1
    mitigation: usercopy/swapgs barriers and __user pointer sanitization
  Type: spectre_v2 mitigation: Retpolines, IBPB: conditional, IBRS_FW,
    STIBP: conditional, RSB filling
  Type: srbds mitigation: Microcode
  Type: tsx_async_abort status: Not affected
Graphics:
  Device-1: Intel UHD Graphics 620 vendor: Acer Incorporated ALI driver: i915
    v: kernel ports: active: eDP-1 empty: DP-1,HDMI-A-1 bus-ID: 00:02.0
    chip-ID: 8086:5917 class-ID: 0300
  Device-2: NVIDIA GP108M [GeForce MX150] vendor: Acer Incorporated ALI
    driver: nvidia v: 515.43.04 alternate: nouveau,nvidia_drm pcie: gen: 3
    speed: 8 GT/s lanes: 4 bus-ID: 01:00.0 chip-ID: 10de:1d10 class-ID: 0302
  Device-3: Chicony HD WebCam type: USB driver: uvcvideo bus-ID: 1-7:4
    chip-ID: 04f2:b571 class-ID: 0e02
  Display: x11 server: X.Org v: 21.1.3 with: Xwayland v: 22.1.1
    compositor: gnome-shell driver: X: loaded: modesetting,nvidia gpu: i915
    display-ID: :1 screens: 1
  Screen-1: 0 s-res: 1920x1080 s-dpi: 96 s-size: 508x286mm (20.00x11.26")
    s-diag: 583mm (22.95")
  Monitor-1: eDP-1 mapped: eDP-1-1 model: Najing CEC Panda LM156LF1L03
    built: 2017 res: 1920x1080 hz: 60 dpi: 142 gamma: 1.2
    size: 344x194mm (13.54x7.64") diag: 395mm (15.5") ratio: 16:9
    modes: 1920x1080
  OpenGL: renderer: NVIDIA GeForce MX150/PCIe/SSE2
    v: 4.6.0 NVIDIA 515.43.04 direct render: Yes
Audio:
  Device-1: Intel Sunrise Point-LP HD Audio vendor: Acer Incorporated ALI
    driver: snd_hda_intel v: kernel alternate: snd_soc_skl bus-ID: 00:1f.3
    chip-ID: 8086:9d71 class-ID: 0403
  Sound Server-1: ALSA v: k5.17.7-arch1-1 running: yes
  Sound Server-2: PulseAudio v: 15.0 running: no
  Sound Server-3: PipeWire v: 0.3.51 running: yes
Network:
  Device-1: Intel Dual Band Wireless-AC 3168NGW [Stone Peak] driver: iwlwifi
    v: kernel pcie: gen: 1 speed: 2.5 GT/s lanes: 1 bus-ID: 03:00.0
    chip-ID: 8086:24fb class-ID: 0280
  IF: wlan0 state: up mac: <filter>
  Device-2: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet
    vendor: Acer Incorporated ALI driver: r8169 v: kernel pcie: gen: 1
    speed: 2.5 GT/s lanes: 1 port: 3000 bus-ID: 04:00.1 chip-ID: 10ec:8168
    class-ID: 0200
  IF: enp4s0f1 state: down mac: <filter>
Bluetooth:
  Device-1: Intel Wireless-AC 3168 Bluetooth type: USB driver: btusb v: 0.8
    bus-ID: 1-5:3 chip-ID: 8087:0aa7 class-ID: e001
  Report: rfkill ID: hci0 rfk-id: 0 state: up address: see --recommends
Drives:
  Local Storage: total: 238.47 GiB used: 130.16 GiB (54.6%)
  SMART Message: Unable to run smartctl. Root privileges required.
  ID-1: /dev/sda maj-min: 8:0 vendor: SK Hynix model: HFS256G39TND-N210A
    size: 238.47 GiB block-size: physical: 4096 B logical: 512 B
    speed: 6.0 Gb/s type: SSD serial: <filter> rev: 1P10 scheme: GPT
Partition:
  ID-1: / raw-size: 229.37 GiB size: 224.71 GiB (97.97%)
    used: 130.16 GiB (57.9%) fs: ext4 dev: /dev/sda2 maj-min: 8:2
  ID-2: /boot/efi raw-size: 300 MiB size: 299.4 MiB (99.80%)
    used: 296 KiB (0.1%) fs: vfat dev: /dev/sda1 maj-min: 8:1
Swap:
  Kernel: swappiness: 60 (default) cache-pressure: 100 (default)
  ID-1: swap-1 type: partition size: 8.8 GiB used: 0 KiB (0.0%)
    priority: -2 dev: /dev/sda3 maj-min: 8:3
Sensors:
  System Temperatures: cpu: 60.0 C pch: 55.5 C mobo: N/A gpu: nvidia
    temp: 51 C
  Fan Speeds (RPM): N/A
Info:
  Processes: 286 Uptime: 7h 31m wakeups: 1 Memory: 15.51 GiB
  used: 4.7 GiB (30.3%) Init: systemd v: 250 tool: systemctl Compilers:
  gcc: 12.1.0 Packages: pacman: 1296 lib: 330 flatpak: 0 Shell: Bash
  v: 5.1.16 running-in: tilix inxi: 3.3.15
```

**Comment by Taiko2k** [comment]
Yep, its a known Arch Linux bug. https://bugs.archlinux.org/task/74611

You can work around it by doing `sudo pacman -S python-httpx`

**Comment by Scotty-Trees** [comment]
Is that supposed to be another dependency that should be included with the AUR package of Tauon or no? Forgive my misunderstanding of the bug. 

Btw, installing `python-httpx` pulls in a bunch of other python packages too, thankfully it's only 1.9MB, but Tauon sure is starting to get extra 'beefy'! :smile: 

```
[scott@endeavourOS ~]$ sudo pacman -S python-httpx
resolving dependencies...
looking for conflicting packages...

Package (11)                         New Version  Net Change  Download Size

community/python-anyio               3.6.1-1        0.83 MiB       0.13 MiB
community/python-certifi             2021.10.8-3    0.26 MiB       0.14 MiB
community/python-charset-normalizer  2.0.10-2       0.31 MiB       0.07 MiB
community/python-commonmark          0.9.1-5        0.62 MiB       0.11 MiB
community/python-docutils            1:0.16-2       4.30 MiB       0.75 MiB
community/python-h11                 0.12.0-3       0.39 MiB       0.08 MiB
community/python-httpcore            0.14.7-1       0.57 MiB       0.08 MiB
community/python-rfc3986             1.5.0-3        0.24 MiB       0.04 MiB
community/python-rich                12.4.1-1       1.83 MiB       0.38 MiB
community/python-sniffio             1.2.0-5        0.02 MiB       0.01 MiB
community/python-httpx               0.22.0-2       0.74 MiB       0.13 MiB

Total Download Size:    1.91 MiB
Total Installed Size:  10.12 MiB

:: Proceed with installation? [Y/n] 
```

**Comment by ManuLinares** [comment]
Hope they fix that dependency upstream

**Comment by Taiko2k** [comment]
It's a dependency of pylast. Adding httpx as a dependency of Tauon would fix it... But it's really arch linuxes job to fix their package, I didn't expect it would take them this long.

You're right about that dependency tree getting long, I should probably look at making pylast optional.

**Comment by Scotty-Trees** [comment]
I've been using Last.fm since like 2004. Having that support in my music software has always been a plus for me, but I don't know if most users use it or not. I think Last.fm was popular for a time, but it's hard to say if it's more or less popular today. In any case, as long as Tauon has Las.fm support either by default OR optional, is still a good thing for myself since I know `python-pylast` is for Last.fm interactions

**Comment by talhakerpicci** [comment]
Hey there. Just recently got this issue. Tauon does not start. Here is the output from the command line:

```
No previous window state
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  152 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  159
  Current serial number in output stream:  160
```

I also have `python-httpx` installed.

Im on arch linux. Running latest our version of the Tauon. Anything i can do to fix this?

**Comment by Scotty-Trees** [comment]
Not a solution per se, but I just use the flatpak version, it just works and I don't have to worry about maintaining two dozen python packages from the Arch and AUR repos :laughing:

**Comment by Taiko2k** [comment]
Im not sure what exactly causes it, but I may be able to fix it next release. If it is what I'm thinking, you should be able to fix it by resetting the app, to do so go to the user app data folder and delete the files 'state.p` and `state.p.backup`, note this will delete all playlists etc. Let me know if that works

**Comment by Taiko2k** [comment]
@ManuLinares Indeed this issue is unrelated to the original. Maybe they assumed it might have been.

@talhakerpicci I've made a new issue for this, let's continue there #768

**Comment by talhakerpicci** [comment]
Oh my bad. The error message seemed similar to the one i am having. Sorry for that

**Comment by talhakerpicci** [comment]
> Im not sure what exactly causes it, but I may be able to fix it next release. If it is what I'm thinking, you should be able to fix it by resetting the app, to do so go to the user app data folder and delete the files `state.p` and `state.p.backup`, note this will delete all playlists etc. Let me know if that works

This worked. All playlists are gone tho as u said. Is there a way to backup playlists just in case for the next time?

**Comment by C0rn3j** [comment]
@Taiko2k Can be closed, was fixed upstream on August 2022.
