### ISSUE TITLE
tauon crashes from time to time

### ISSUE THREAD

**Issue by legacychimera247** [Taiko2k/Tauon#930]
hello, sometimes it happens that if i leave tauon open for a while whitout listening to music, it crashes, and i have the system notification that python 3.10 has crashed, don't know if it's because i'm on fedora 38, which is still 37 under the hood, but it has been happening from latest tauon update...

**Comment by Taiko2k** [comment]
Try start tauon from terminal and see if you can catch the error it puts out.

**Comment by legacychimera247** [comment]
here is it

`** (tauon.py:3): WARNING **: 16:26:29.204: atk-bridge: get_device_events_reply: unknown signature
/app/bin/com.github.taiko2k.tauonmb.sh: riga 14:     3 Errore di segmentazione (core dump creato) python3 /app/bin/tauon.py "$@"
[luca247@fedora ~]$ 
`

**Comment by legacychimera247** [comment]
any update on this?it's still crashing but now with python 3.11, despite fedora using 3.12 now...

**Comment by legacychimera247** [comment]
any update on this?asking cause it's crashing that often, especially when suspend is triggered

by the way, it's crashing stating that 3.11 has crashed, despite being superseded in fedora by python 3.12...

**Comment by C0rn3j** [comment]
Suspend issues already have a thread here you can post in https://github.com/Taiko2k/Tauon/issues/1260

I imagine you'll need to provide the backtrace from the coredump for anyone to make heads and tails of the issue.

> by the way, it's crashing stating that 3.11 has crashed, despite being superseded in fedora by python 3.12...

Installed how, Flatpak? Because that would have its own versions.

**Comment by legacychimera247** [comment]
installed this as flatpak yes

i will make a separate thread then as i noticed that screen goes in suspend even if no suspend is selected on tauon...

**Comment by C0rn3j** [comment]
Can you retest on pre-release 7.9.0 flatpak?

See this comment https://github.com/Taiko2k/Tauon/issues/1084#issuecomment-2571286287 for more details.

**Comment by C0rn3j** [comment]
I've posted a new version with a fix on that comment, try that please.

**Comment by legacychimera247** [comment]
installed v2 and still crashes on start

maybe i need to delete some config files first?

**Comment by C0rn3j** [comment]
Can you send the new log?

**Comment by legacychimera247** [comment]
`2025-01-04 19:41:28 [ INFO  ] [ __main__ ] Tauon v7.9.0
2025-01-04 19:41:28 [ INFO  ] [ __main__ ] Copyright 2015-2025 Taiko2k captain.gxj@gmail.com


(__main__.py:3): Gtk-WARNING **: 19:41:28.330: gtk_disable_setlocale() must be called before gtk_init()
2025-01-04 19:41:28 [ INFO  ] [  t_draw  ] Found jxlpy for JPEG XL support
2025-01-04 19:41:28 [WARNING] [  t_spot  ] Unable to import Tekore, Spotify support will be disabled. (t_spot.py:46)
2025-01-04 19:41:28 [ INFO  ] [  t_main  ] Window size: [1920, 1048]
2025-01-04 19:41:28 [ INFO  ] [  t_main  ] Detected running as Flatpak
2025-01-04 19:41:28 [ INFO  ] [  t_main  ] Installed as Flatpak
2025-01-04 19:41:28 [ INFO  ] [  t_main  ] Install directory:         /app/bin/src/tauon
2025-01-04 19:41:28 [ INFO  ] [  t_main  ] Asset directory:           /app/bin/src/tauon/assets
2025-01-04 19:41:28 [ INFO  ] [  t_main  ] Locale directory:          /app/bin/src/tauon/locale
2025-01-04 19:41:28 [ INFO  ] [  t_main  ] Userdata directory:        /home/luca247/.var/app/com.github.taiko2k.tauonmb/data/TauonMusicBox
2025-01-04 19:41:28 [ INFO  ] [  t_main  ] Config directory:          /home/luca247/.var/app/com.github.taiko2k.tauonmb/data/TauonMusicBox
2025-01-04 19:41:28 [ INFO  ] [  t_main  ] Cache directory:           /home/luca247/.var/app/com.github.taiko2k.tauonmb/cache/TauonMusicBox
2025-01-04 19:41:28 [ INFO  ] [  t_main  ] Home directory:            /home/luca247
2025-01-04 19:41:28 [ INFO  ] [  t_main  ] Music directory:           /home/luca247/Musica
2025-01-04 19:41:28 [ INFO  ] [  t_main  ] Downloads directory:       /home/luca247/Scaricati
2025-01-04 19:41:29 [ ERROR ] [  t_main  ] Failed to run flatpak-spawn (t_main.py:754)
Traceback (most recent call last):
  File "/app/bin/src/tauon/t_modules/t_main.py", line 747, in whicher
    complete = subprocess.run(
               ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['flatpak-spawn', '--host', 'which', 'unrar']' returned non-zero exit status 1.
2025-01-04 19:41:29 [ ERROR ] [  t_main  ] Failed to run flatpak-spawn (t_main.py:754)
Traceback (most recent call last):
  File "/app/bin/src/tauon/t_modules/t_main.py", line 747, in whicher
    complete = subprocess.run(
               ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['flatpak-spawn', '--host', 'which', '7z']' returned non-zero exit status 1.
2025-01-04 19:41:29 [WARNING] [  t_main  ] Loaded older DB version: 68 (t_main.py:2762)
2025-01-04 19:41:29 [ INFO  ] [  t_main  ] Database loaded in 0.077 seconds.
2025-01-04 19:41:29 [WARNING] [  t_main  ] Current DB version 68 was lower than latest 69, running migrations! (t_main.py:3197)
2025-01-04 19:41:29 [WARNING] [t_db_migrate] Running migrations as DB version was 68! (t_db_migrate.py:55)
2025-01-04 19:41:29 [ INFO  ] [t_db_migrate] Updating database to version 69
2025-01-04 19:41:29 [ INFO  ] [  t_main  ] Translation file for 'None' loaded
2025-01-04 19:41:29 [WARNING] [  t_main  ] Unable to import Chrome(pychromecast), chromecast support will be disabled. (t_main.py:8938)
2025-01-04 19:41:29 [ ERROR ] [  t_main  ] Failed to load libXcursor.so, will try libXcursor.so.1 (t_main.py:10445)
Traceback (most recent call last):
  File "/app/bin/src/tauon/t_modules/t_main.py", line 10443, in <module>
    xcu = ctypes.cdll.LoadLibrary("libXcursor.so")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ctypes/__init__.py", line 460, in LoadLibrary
    return self._dlltype(name)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ctypes/__init__.py", line 379, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: libXcursor.so: impossibile aprire il file oggetto condiviso: File o directory non esistente
2025-01-04 19:41:29 [ INFO  ] [t_webserve] Start controller server
2025-01-04 19:41:29 [ INFO  ] [  t_main  ] Using SDL version: 2.30.9
2025-01-04 19:41:29 [ INFO  ] [  t_main  ] Applying theme: Sky
2025-01-04 19:41:29 [ INFO  ] [  t_main  ] Auto save playtime
Traceback (most recent call last):
  File "/app/bin/src/tauon/__main__.py", line 450, in <module>
    main()
  File "/app/bin/src/tauon/__main__.py", line 447, in main
    from tauon.t_modules import t_main
  File "/app/bin/src/tauon/t_modules/t_main.py", line 45977, in <module>
    artist_list_box.render(*panel_rect)
  File "/app/bin/src/tauon/t_modules/t_main.py", line 37994, in render
    self.draw_card(artist, x, round(yy), w)
  File "/app/bin/src/tauon/t_modules/t_main.py", line 37697, in draw_card
    self.draw_card_with_thumbnail(artist, x, y, w, area, thin_mode, line1_colour, line2_colour, light_mode, bg)
  File "/app/bin/src/tauon/t_modules/t_main.py", line 37513, in draw_card_with_thumbnail
    self.load_img(artist)
  File "/app/bin/src/tauon/t_modules/t_main.py", line 37226, in load_img
    filepath = artist_info_box.get_data(artist, get_img_path=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bin/src/tauon/t_modules/t_main.py", line 39841, in get_data
    str(user_directory / "artist-pictures" / f_artist + ".png"),
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
TypeError: unsupported operand type(s) for +: 'PosixPath' and 'str'`

**Comment by C0rn3j** [comment]
That PosifxPath+str error is already fixed, I apparently managed to build the wrong version, try again with v3+ please.

**Comment by legacychimera247** [comment]
ok this one installed right, i'll let you know...

**Comment by legacychimera247** [comment]
i know it's too early to say, but i opened tauon v3 and without playing anything i let the screen go into suspend

it didn't crash, while on 7.8.0 it would probably have crashed as soon as the screen was black

i noticed there is a v5, what's changing from v3?

**Comment by C0rn3j** [comment]
> i noticed there is a v5, what's changing from v3?

It has this https://github.com/Taiko2k/Tauon/pull/1375

**Comment by legacychimera247** [comment]
not sporadic, tauon crashed pratically every single time it was open after a suspend or sometimes not being in focus, but still, better to leave this open for some more days so i can test it better :)

**Comment by legacychimera247** [comment]
done some further tests, seems like it's solved :)

**Comment by C0rn3j** [comment]
Then the official 7.9.0 update which will come out sometime in the future should deal with it, thanks for testing!
