### ISSUE TITLE
AUR: Tauon won't start, manual intervention required

### ISSUE THREAD

**Issue by Taiko2k** [Taiko2k/Tauon#985]
With the release of Python 3.13, 3.14 etc, you need to rebuild AUR python dependencies.

For Tauon, run:

```bash
# Replace trizen with your AUR helper of choice, or build the packages manually

# Clear cache to not accidentally use an old build
trizen -Scc

# Rebuild the package(s)
trizen -S python-pysdl3 # or other dependencies that were not rebuilt and are throwing an error
```

**Comment by rstrube** [comment]
Thank you, I was just about to create an issue for this!

**Comment by Qwerty-Space** [comment]
Even after manually installing these packages, tauon still thinks isounidecode isn't installed

**Comment by kamu106** [comment]
Even after manually installing these packages, tauon still thinks isounidecode isn't installed and still returns the same Error

Tauon Music Box v7.7.0
Copyright 2015-2023 Taiko2k captain.gxj@gmail.com

No window state file
Window size: [1120, 600]

(tauon.py:24550): Gtk-WARNING **: 07:17:03.666: Theme parsing error: gtk.css:6616:68: Invalid name of pseudo-class
Running from installed location
User files location: /root/.local/share/TauonMusicBox
Install directory: /opt/tauon-music-box
Input config file is missing... copying template from program files
Traceback (most recent call last):
  File "/opt/tauon-music-box/tauon.py", line 359, in <module>
    exec(main)
  File "/opt/tauon-music-box/t_modules/t_main.py", line 579, in <module>
    from isounidecode import unidecode
ModuleNotFoundError: No module named 'isounidecode'

**Comment by kamu106** [comment]
Thanks for the quick reply, 

python-isounidecode /usr/
python-isounidecode /usr/lib/
python-isounidecode /usr/lib/python3.10/
python-isounidecode /usr/lib/python3.10/site-packages/
python-isounidecode /usr/lib/python3.10/site-packages/isounidecode-0.3-py3.10.egg-info
python-isounidecode /usr/lib/python3.10/site-packages/isounidecode/
python-isounidecode /usr/lib/python3.10/site-packages/isounidecode/__init__.py
python-isounidecode /usr/lib/python3.10/site-packages/isounidecode/__pycache__/
python-isounidecode /usr/lib/python3.10/site-packages/isounidecode/__pycache__/__init__.cpython-310.opt-1.pyc
python-isounidecode /usr/lib/python3.10/site-packages/isounidecode/__pycache__/__init__.cpython-310.pyc
python-isounidecode /usr/lib/python3.10/site-packages/isounidecode/__pycache__/__init__.cpython-35.pyc
python-isounidecode /usr/lib/python3.10/site-packages/isounidecode/__pycache__/codes.cpython-310.opt-1.pyc
python-isounidecode /usr/lib/python3.10/site-packages/isounidecode/__pycache__/codes.cpython-310.pyc
python-isounidecode /usr/lib/python3.10/site-packages/isounidecode/__pycache__/codes.cpython-35.pyc
python-isounidecode /usr/lib/python3.10/site-packages/isounidecode/__pycache__/unidecode.cpython-310.opt-1.pyc
python-isounidecode /usr/lib/python3.10/site-packages/isounidecode/__pycache__/unidecode.cpython-310.pyc
python-isounidecode /usr/lib/python3.10/site-packages/isounidecode/__pycache__/unidecode.cpython-35.pyc
python-isounidecode /usr/lib/python3.10/site-packages/isounidecode/codes.py
python-isounidecode /usr/lib/python3.10/site-packages/isounidecode/unidecode.py

**Comment by Taiko2k** [comment]
@kamu106 Yep looks like its not installed for 3.11. you need to rebuild and reinstall the isounidecode package. If you already tried that you probably need to wipe your AUR helpers cache or build it manually. To build manually:

`git clone https://aur.archlinux.org/python-isounidecode.git`
`cd python-isounidecode`
`makepkg -si`

**Comment by kamu106** [comment]
> cd python-isounidecode

Thanks that fixed it, thanks for all your hard work

**Comment by TheFlomax** [comment]
Hey, I installed the missing dependencies and reinstalled Tauon, but at home the problem persists.
![image](https://github.com/user-attachments/assets/be6eaf47-30dd-464a-8cec-4320f45ca6ce)

**Comment by C0rn3j** [comment]
>  I installed the missing dependencies

You need to rebuild and reinstall your current packages instead (in this case pysdl2).

The 3.11 dependency (isounidecode) is no longer used in current Tauon.

**Comment by TheFlomax** [comment]
> You need to rebuild and reinstall your current packages instead (in this case pysdl2).

And how can I do that with paru or pacman?
Sorry, I'm not used to this kind of manipulation.

**Comment by C0rn3j** [comment]
As per the example in the OP - https://github.com/Taiko2k/Tauon/issues/985#issue-1695127595 - minus the isounidecode package.

**Comment by TheFlomax** [comment]
> As per the example in the OP - [#985 (comment)](https://github.com/Taiko2k/Tauon/issues/985#issue-1695127595) - minus the isounidecode package.

Okay so I have try with `paru -S tauon-music-box python-pysdl2` but I have get the same error.
So I have so an `paru -Rns tauon-music-box python-pysdl2` and I retry `paru -S tauon-music-box python-pysdl2`.

But I have the same error.

![image](https://github.com/user-attachments/assets/2a7bf44a-fee9-496b-b67b-b207941eaab2)

**Comment by TheFlomax** [comment]
> `pacman -Qoq /usr/lib/python3.12/site-packages/` -> this should return an error, if it returns any packages, they're broken, remove them and reinstall them if you need them.
> 
> `ls -lah /usr/lib/python3.12` - This should return an error - if the first command now returns an error, but this one doesn't, look what's in there, figure out how it got there, then delete it and don't make that mistake again.
> 
> `echo ~/.local/lib/python*` This should return an error - if not - delete the result after figuring out how it got there.
> 
> If you're STILL getting issues, show `pacman -Qi python-pysdl2` and
> 
> ```
> python
> >>> import sdl2
> ```

I have get no error but import sdl2 are fail.

![image](https://github.com/user-attachments/assets/9d12a2b6-5dc4-4b9e-a726-84337f608971)

**Comment by C0rn3j** [comment]
Your package is compiled in November, you're reinstalling an old version over and over.

`paru -Scc` to clear the cache.

**Comment by TheFlomax** [comment]
> Your package is compiled in November, you're reinstalling an old version over and over.
> `paru -Scc` to clear the cache.

Ahhh, yes i right now Tauon is work !
![image](https://github.com/user-attachments/assets/60c2d276-fa0c-4dc8-bae5-729566457bb4)

**Comment by C0rn3j** [comment]
I think we can close this, now that Tauon is in official repositories
